### ISSUE TITLE
please document "API" for starting stacker

### ISSUE THREAD

**Issue by bremner** [LuKuangChen/stacker-2023#5]
There are several URL parameters, but I don't think they are documented anywhere. Please document those that you think are stable, so that others can use them to e.g. start up stacker with a given program.

**Comment by LuKuangChen** [comment]
@bremner please check the new README and feel free to let me know if there is anything unclear or can be improved.

**Comment by bremner** [comment]
KC Lu ***@***.***> writes:

> @bremner please check the new README and feel free to let me know if there is anything unclear or can be improved.
>

Thanks, it looks good to me

d
