### ISSUE TITLE
provide more controls for text size, window size

### ISSUE THREAD

**Issue by bremner** [LuKuangChen/stacker-2023#8]
I have started using stacker on an overhead projector, and I am having trouble making the program (and to a lesser extent VM / heap / etc..) text readable without zooming the VM (right hand side). I think it would help if I could increase the text size without zooming the whole stacker tab. 

A second thing that I wanted at some point was to be able to change the split between input and the VM display.

Apologies if this is just me not being very expert with manipulating browsers. I am almost exclusively using Firefox, if that helps.

**Comment by LuKuangChen** [comment]
Thanks for the feedback! All these features make perfect sense. I can imagine myself wanting these features :)

I probably can't make these improvements before mid 2024. But they will certainly be there in the next big update.
